dataset: CIFAR10
device: [0,1,2,3]

ipc: 50
syn_steps: 80
expert_epochs: 2
lr_img: 1000
lr_teacher: 0.01
buffer_path: /home/kwang/big_space/lzk/buffer_storage/cifar10/
data_path: /home/kwang/big_space/lzk/dataset
ema_decay: 0.995
Iteration: 20000
batch_syn: 500

# wandb
project: LRI-DD
name: cifar10_ipc50_loss_scaled_activation_alter_100_dyn_res50_map

num_eval: 1
eval_it: 500
skip_first_eva: False

lr_y: 2.
Momentum_y: 0.9
threshold: 1.
pix_init: samples_predicted_correctly
expansion_end_epoch: 2000
batch_train: 128
min_start_epoch: 0
current_max_start_epoch: 20
max_start_epoch: 40
lr_lr: 0.00001
zca: True

interval: 100
loss_threshold: 0.5
activation_model_path: /home/kwang/big_space/lzk/cifar_models/CIFAR10/ResNet50_best.pt