dataset: CIFAR10
device: [0,1,2,4]

ipc: 50
syn_steps: 80
expert_epochs: 2
lr_img: 1000
lr_teacher: 0.01
buffer_path: /home/kwang/big_space/lzk/buffer_storage/cl_grand_75_20_01/
data_path: ../dataset
ema_decay: 0.995
Iteration: 10000
batch_syn: 500

# wandb
project: CIFAR10_ipc50
name: cl_grand_75_20_01

num_eval: 1
eval_it: 500
skip_first_eva: False

lr_y: 2.
Momentum_y: 0.9
threshold: 1.
pix_init: samples_predicted_correctly
expansion_end_epoch: 2000
batch_train: 128
min_start_epoch: 0
current_max_start_epoch: 20
max_start_epoch: 40
lr_lr: 0.00001
zca: True

# loss_threshold_low: 0.5
# loss_threshold_high: 1.0
